/* =====================================================================
 * Auto-generated by sidlc v0.1.0 (c706d49)
 * Target Interface: Block
 * DO NOT EDIT THIS FILE MANUALLY!
 * ===================================================================== */

#ifndef __SIDL_INTERFACE_BLOCK_HH__
#define __SIDL_INTERFACE_BLOCK_HH__

#include <stdint.h>

#include <strata/status.h>
#include <strata/macros.h>
#include <strata/uuid.h>

/* Constants & Bitmasks */
#define UUID_BLOCK_INTERFACE ((struct StUuid){ 0x8c, 0x11, 0xce, 0x10, 0x66, 0xd8, 0x5e, 0x14, 0x8a, 0xdf, 0x2b, 0x9e, 0xef, 0x46, 0xe2, 0xf7, });

/* ABI Version 0 */
#define IOFLAGS_DIRECT (1ULL << 0)

/* Types & Structures */

/* ABI Version 0 */
struct StIfBlk_IoRequest {
    void *buf;
    uint64_t size;
};

struct StIfBlk_IoResult {
    uint64_t reqid;
    uint64_t status;
    uint64_t xfer_size;
} __attribute__((aligned(16)));

typedef uint32_t StIfBlk_IoFlags;

/* Functions & Views */

/* ABI Version 0 */
StStatus StIfBlk_Read(StHandle handle __in, uint64_t start_lba __in, const StIfBlk_IoRequest *ioreqvec __in, uint64_t ioreq_size __in, uint64_t ioreq_count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out);
StStatus StIfBlk_Write(StHandle handle __in, uint64_t start_lba __in, const StIfBlk_IoRequest *ioreqvec __in, uint64_t ioreq_size __in, uint64_t ioreq_count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out);
StStatus StIfBlk_Flush(StHandle handle __in, uint64_t start_lba __in, uint64_t count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out);
StStatus StIfBlk_Discard(StHandle handle __in, uint64_t start_lba __in, uint64_t count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out);
StStatus StIfBlk_CheckStatus(StHandle handle __in, uint64_t reqid __in, uint64_t *status __out);
StStatus StIfBlk_Wait(StHandle handle __in, StIfBlk_IoResult *ioresvec __in, uint64_t iores_size __in, uint64_t max_iores_count __in, uint64_t min_iores_count __in, uint64_t timeout_ms __in, uint64_t *filled_iores_count __out);
StStatus StIfBlk_Cancel(StHandle handle __in, uint64_t reqid __in);
StStatus StIfBlk_GetBlockSize(StHandle handle __in, uint64_t *block_size __out);
StStatus StIfBlk_SetBlockSize(StHandle handle __in, uint64_t block_size __in);
StStatus StIfBlk_GetMaxLba(StHandle handle __in, uint64_t *max_lba __out);

#endif /* __SIDL_INTERFACE_BLOCK_HH__ */
