/* =====================================================================
 * Auto-generated by sidlc v0.1.0 (c706d49)
 * Target Interface: Block
 * DO NOT EDIT THIS FILE MANUALLY!
 * ===================================================================== */

#include "block.h"

#include <strata/status.h>
#include <strata/macros.h>
#include <strata/uuid.h>
#include <strata/krt.h>

/* Constants & Bitmasks */

/* Group Default */

/* ABI Version 0 */
#define FUNCID_Read 0
#define FUNCID_Write 1
#define FUNCID_Flush 2
#define FUNCID_Discard 3
#define FUNCID_CheckStatus 4
#define FUNCID_Wait 5
#define FUNCID_Cancel 6
#define FUNCID_GetBlockSize 7
#define FUNCID_SetBlockSize 8
#define FUNCID_GetMaxLba 9

extern __get_func_id_base(StHandle handle __in, const struct StUuid *uuid __in, uint32_t request_groupid __in, uint32_t request_abiver __in, uint32_t *funcid_base __out, uint32_t *result_abiver __out);

/* Functions & Views */

/* Group Default */

/* ABI Version 0 */
StStatus StIfBlk_Read(StHandle handle __in, uint64_t start_lba __in, const StIfBlk_IoRequest *ioreqvec __in, uint64_t ioreq_size __in, uint64_t ioreq_count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t start_lba;
        const StIfBlk_IoRequest *ioreqvec;
        uint64_t ioreq_size;
        uint64_t ioreq_count;
        StIfBlk_IoFlags flags;
    } __packed in;
    struct {
        uint64_t reqid;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_Read, &in, sizeof(in), &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_Write(StHandle handle __in, uint64_t start_lba __in, const StIfBlk_IoRequest *ioreqvec __in, uint64_t ioreq_size __in, uint64_t ioreq_count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t start_lba;
        const StIfBlk_IoRequest *ioreqvec;
        uint64_t ioreq_size;
        uint64_t ioreq_count;
        StIfBlk_IoFlags flags;
    } __packed in;
    struct {
        uint64_t reqid;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_Write, &in, sizeof(in), &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_Flush(StHandle handle __in, uint64_t start_lba __in, uint64_t count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t start_lba;
        uint64_t count;
        StIfBlk_IoFlags flags;
    } __packed in;
    struct {
        uint64_t reqid;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_Flush, &in, sizeof(in), &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_Discard(StHandle handle __in, uint64_t start_lba __in, uint64_t count __in, StIfBlk_IoFlags flags __in, uint64_t *reqid __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t start_lba;
        uint64_t count;
        StIfBlk_IoFlags flags;
    } __packed in;
    struct {
        uint64_t reqid;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_Discard, &in, sizeof(in), &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_CheckStatus(StHandle handle __in, uint64_t reqid __in, uint64_t *status __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t reqid;
    } __packed in;
    struct {
        uint64_t status;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_CheckStatus, &in, sizeof(in), &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_Wait(StHandle handle __in, StIfBlk_IoResult *ioresvec __in, uint64_t iores_size __in, uint64_t max_iores_count __in, uint64_t min_iores_count __in, uint64_t timeout_ms __in, uint64_t *filled_iores_count __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        StIfBlk_IoResult *ioresvec;
        uint64_t iores_size;
        uint64_t max_iores_count;
        uint64_t min_iores_count;
        uint64_t timeout_ms;
    } __packed in;
    struct {
        uint64_t filled_iores_count;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_Wait, &in, sizeof(in), &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_Cancel(StHandle handle __in, uint64_t reqid __in)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t reqid;
    } __packed in;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_Cancel, &in, sizeof(in), NULL, 0);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_GetBlockSize(StHandle handle __in, uint64_t *block_size __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t block_size;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_GetBlockSize, NULL, 0, &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_SetBlockSize(StHandle handle __in, uint64_t block_size __in)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t block_size;
    } __packed in;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_SetBlockSize, &in, sizeof(in), NULL, 0);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}

StStatus StIfBlk_GetMaxLba(StHandle handle __in, uint64_t *max_lba __out)
{
    uint32_t funcid;
    StStatus _status;
    struct {
        uint64_t max_lba;
    } __packed out;
    _status = __get_func_id_base(handle, &UUID_BLOCK_INTERFACE, 0, 0, &funcid, NULL);
    if (!CHECK_SUCCESS(_status)) { return _status; }
    _status = StKrt_Call(handle, FUNCID_GetMaxLba, NULL, 0, &out, sizeof(out));
    if (!CHECK_SUCCESS(_status)) { return _status; }
    return STATUS_SUCCESS;
}


