#include <c_header_generator.hh>

#include <algorithm>
#include <cctype>
#include <stdexcept>

#include <uuid.h>

#include <arch_abi.hh>
#include <ast.hh>

#include "config.h"

std::string CHeaderGenerator::get_parameter_c_type(const ParameterNode &node)
{
    bool add_pointer = node.direction != ParameterNode::Direction::IN;

    if (node.type->is_ptr) {
        return to_c_type(prefix, *node.type) + (add_pointer ? "*" : "");
    }

    return to_c_type(prefix, *node.type) + (add_pointer ? " *" : "");
}

void CHeaderGenerator::write_parameter_declaration(std::ostream &stream, const ParameterNode &node)
{
    stream << get_parameter_c_type(node) << " " << node.name;

    switch (node.direction) {
    case ParameterNode::Direction::IN:
        stream << " __in";
        break;
    case ParameterNode::Direction::OUT:
        stream << " __out";
        break;
    case ParameterNode::Direction::INOUT:
        stream << " __inout";
        break;
    }
}

void CHeaderGenerator::visit(InterfaceNode &node)
{
    const bool is_type_header = mode == Mode::TYPE;
    const bool is_client_header = mode == Mode::CLIENT;
    const bool is_server_header = mode == Mode::SERVER;
    const bool is_server_client_header = mode == Mode::SERVER_CLIENT;
    size_t server_arg_slot_count = 0;

    prefix.clear();
    macro_prefix.clear();
    macro_interface_name.clear();
    total_funcid_span = 0;
    abi_revision_count = 0;

    if (is_server_header) {
        if (!g_current_arch_abi || g_current_arch_abi->max_reg_args <= 2) {
            throw std::runtime_error("Invalid architecture ABI");
        }

        server_arg_slot_count = g_current_arch_abi->max_reg_args - 2;
    }

    buf_macros.str("");
    buf_macros.clear();
    buf_types.str("");
    buf_types.clear();
    buf_functions.str("");
    buf_functions.clear();
    buf_module_vtable_fields.str("");
    buf_module_vtable_fields.clear();

    macro_interface_name = node.name;
    std::transform(
        macro_interface_name.begin(),
        macro_interface_name.end(),
        macro_interface_name.begin(),
        [](unsigned char ch) {
            return static_cast<char>(std::toupper(ch));
        }
    );

    if (!node.has_uuid) {
        throw std::runtime_error("Interface UUID is required");
    }
    if (!node.has_prefix) {
        throw std::runtime_error("Interface prefix is required");
    }

    prefix = node.prefix;
    macro_prefix = prefix;
    std::transform(
        macro_prefix.begin(),
        macro_prefix.end(),
        macro_prefix.begin(),
        [](unsigned char ch) {
            return static_cast<char>(std::toupper(ch));
        }
    );

    uuids::uuid_name_generator gen(uuids::uuid(node.uuid_namespace));
    auto final_uuid = gen(node.uuid_name);
    std::span<const std::byte, 16> bytes = final_uuid.as_bytes();

    buf_macros << "#define UUID_" << macro_interface_name << "_INTERFACE_INIT UUID_INIT("
               << std::hex;
    for (size_t i = 0; i < bytes.size(); ++i) {
        buf_macros << "0x" << static_cast<int>(bytes[i]);
        if (i + 1 < bytes.size()) {
            buf_macros << ", ";
        }
    }
    buf_macros << std::dec << ")\n";

    buf_macros << "#define UUID_" << macro_interface_name << "_INTERFACE UUID(" << std::hex;
    for (size_t i = 0; i < bytes.size(); ++i) {
        buf_macros << "0x" << static_cast<int>(bytes[i]);
        if (i + 1 < bytes.size()) {
            buf_macros << ", ";
        }
    }
    buf_macros << std::dec << ")\n";

    for (const auto &anno : node.annotations) {
        if (anno->name == "prefix") {
            throw std::runtime_error("Prefix must be stored as interface metadata, not annotation");
        } else if (anno->name == "uuid") {
            throw std::runtime_error("UUID must be stored as interface identity, not annotation");
        }
    }

    for (const auto &abi : node.abiversions) {
        abi->accept(*this);
    }

    buf_macros << "#define " << macro_prefix << "FUNCID_SPAN " << total_funcid_span << "\n";
    buf_macros << "#define " << macro_prefix << "ABI_REVISION_COUNT " << abi_revision_count << "\n";

    out << "/* =====================================================================\n";
    out << " * Auto-generated by sidlc v" << SIDLC_VERSION << " (" << SIDLC_GIT_HASH << ")\n";
    out << " * Target Interface: " << node.name << "\n";
    out << " * DO NOT EDIT THIS FILE MANUALLY!\n";
    out << " * ===================================================================== */\n\n";

    if (is_type_header) {
        out << "#ifndef __SIDL_INTERFACE_" << macro_interface_name << "_TYPES_H__\n";
        out << "#define __SIDL_INTERFACE_" << macro_interface_name << "_TYPES_H__\n\n";
        out << "#include <stdint.h>\n\n";
        out << "#include <strata/status.h>\n";
        out << "#include <strata/macros.h>\n";
        out << "#include <strata/handle.h>\n\n";
        out << "#include <strata/uuid.h>\n\n";

        if (buf_macros.tellp() > 0) {
            out << "/* Constants & Bitmasks */\n";
            out << buf_macros.str() << "\n";
        }

        if (buf_types.tellp() > 0) {
            out << "/* Types & Structures */\n";
            out << buf_types.str() << "\n";
        }

        out << "#endif /* __SIDL_INTERFACE_" << macro_interface_name << "_TYPES_H__ */\n";
        return;
    }

    if (is_client_header || is_server_client_header) {
        out << "#ifndef __SIDL_INTERFACE_" << macro_interface_name
            << (is_server_client_header ? "_SERVER_CLIENT_H__\n" : "_CLIENT_H__\n");
        out << "#define __SIDL_INTERFACE_" << macro_interface_name
            << (is_server_client_header ? "_SERVER_CLIENT_H__\n\n" : "_CLIENT_H__\n\n");
        out << "#include \"" << dependency_header_name << "\"\n\n";

        if (is_client_header) {
            out << "StStatus " << prefix
                << "Open(const uint8_t *path __in, uint32_t flags __in, StHandle *handle __out);\n";
            out << "StStatus " << prefix
                << "Query(StHandle handle __in, uint32_t request_abiver __in, "
                   "uint32_t *funcid_base __out, uint32_t *result_abiver __out);\n";
            out << "\n";
        }

        if (buf_functions.tellp() > 0) {
            out << "/* Functions & Views */\n";
            out << buf_functions.str() << "\n";
        }

        out << "#endif /* __SIDL_INTERFACE_" << macro_interface_name
            << (is_server_client_header ? "_SERVER_CLIENT_H__" : "_CLIENT_H__") << " */\n";
        return;
    }

    if (is_server_header) {
        out << "#ifndef __SIDL_INTERFACE_" << macro_interface_name << "_SERVER_H__\n";
        out << "#define __SIDL_INTERFACE_" << macro_interface_name << "_SERVER_H__\n\n";
        out << "#include \"" << dependency_header_name << "\"\n\n";

        out << "/* Server Interface */\n";
        out << "typedef struct " << prefix << "ServerVTable {\n";
        out << buf_module_vtable_fields.str();
        out << "} " << prefix << "ServerVTable;\n\n";
        out << "StStatus " << prefix << "ServerDispatchArgs(\n";
        out << "    const void *vtable __in,\n";
        out << "    void *context __inout,\n";
        out << "    StHandle handle __in,\n";
        out << "    uint32_t funcid __in,\n";
        out << "    const long args[" << server_arg_slot_count << "]\n";
        out << ");\n\n";
        out << "#endif /* __SIDL_INTERFACE_" << macro_interface_name << "_SERVER_H__ */\n";
        return;
    }
}

void CHeaderGenerator::visit(AbiversionNode &node)
{
    size_t revision_count = static_cast<size_t>(node.version) + 1;

    if (!node.bitfields.empty() || !node.enums.empty() || !node.functions.empty()) {
        buf_macros << "\n/* ABI Version " << node.version << " */\n";
    }

    if (!node.structs.empty() || !node.bitfields.empty() || !node.enums.empty()) {
        buf_types << "\n/* ABI Version " << node.version << " */\n";
    }

    if (!node.functions.empty()) {
        buf_functions << "\n/* ABI Version " << node.version << " */\n";
        buf_module_vtable_fields << "\n    /* ABI Version " << node.version << " */\n";
    }

    for (const auto &b : node.bitfields) {
        b->accept(*this);
    }

    for (const auto &e : node.enums) {
        e->accept(*this);
    }

    for (const auto &s : node.structs) {
        s->accept(*this);
    }

    for (const auto &f : node.functions) {
        f->accept(*this);
    }

    abi_revision_count = std::max(abi_revision_count, revision_count);
    if (!node.functions.empty()) {
        total_funcid_span = node.functions.back()->id + 1;
    }
}

void CHeaderGenerator::visit(StructNode &node)
{
    std::string attributes = "";

    for (const auto &anno : node.annotations) {
        if (anno->name == "align_size" && !anno->args.empty()) {
            attributes += " __attribute__((aligned(16)))";
        }
    }

    buf_types << "typedef struct " << prefix << node.name << " {\n";

    for (const auto &field : node.fields) {
        if (field->type->is_ptr) {
            buf_types << "    " << to_c_type(prefix, *field->type) << field->name << ";\n";
        } else if (field->type->is_array) {
            buf_types << "    " << to_c_type(prefix, *field->type) << " " << field->name << "[];\n";
        } else {
            buf_types << "    " << to_c_type(prefix, *field->type) << " " << field->name << ";\n";
        }
    }

    buf_types << "}" << attributes << " " << prefix << node.name << ";\n\n";
}

void CHeaderGenerator::visit(BitfieldNode &node)
{
    uint64_t offset = 0;
    std::string macro_name = std::string(node.name);
    std::transform(
        macro_name.begin(),
        macro_name.end(),
        macro_name.begin(),
        [](unsigned char ch) {
            return static_cast<char>(std::toupper(ch));
        }
    );

    buf_types << "typedef " << to_c_type(prefix, *node.base_type) << " " << prefix << node.name
              << ";\n";

    for (const auto &field : node.fields) {
        buf_macros << "#define " << macro_interface_name << "_" << macro_name << "_" << field->name
                   << " (" << (1ULL << field->bits) - 1 << "ULL << " << offset << ")\n";
        offset += field->bits;
    }
}

void CHeaderGenerator::visit(EnumNode &node)
{
    std::string macro_name = std::string(node.name);
    std::transform(
        macro_name.begin(),
        macro_name.end(),
        macro_name.begin(),
        [](unsigned char ch) {
            return static_cast<char>(std::toupper(ch));
        }
    );

    buf_types << "typedef " << to_c_type(prefix, *node.base_type) << " " << prefix << node.name
              << ";\n";

    for (const auto &member : node.members) {
        buf_macros << "#define " << macro_interface_name << "_" << macro_name << "_" << member->name
                   << " (" << member->value << ")\n";
    }
}

void CHeaderGenerator::visit(FunctionNode &node)
{
    buf_macros << "#define " << macro_prefix << "FUNCID_" << node.name << " " << node.id << "\n";

    buf_module_vtable_fields << "    StStatus (*" << node.name
                             << ")(void *context __inout, StHandle handle __in";
    if (!node.parameters.empty()) {
        buf_module_vtable_fields << ", ";
    }

    if (node.parameters.empty()) {
        buf_functions << "StStatus " << prefix << node.name << "(StHandle handle __in";
    } else {
        buf_functions << "StStatus " << prefix << node.name << "(StHandle handle __in, ";
    }

    for (const auto &param : node.parameters) {
        write_parameter_declaration(buf_functions, *param);
        write_parameter_declaration(buf_module_vtable_fields, *param);

        if (&param != &node.parameters.back()) {
            buf_functions << ", ";
            buf_module_vtable_fields << ", ";
        }
    }

    buf_functions << ");\n";
    buf_module_vtable_fields << ");\n";
}
