#include <c_module_source_generator.hh>

#include <algorithm>
#include <cctype>
#include <stdexcept>

#include <uuid.h>

#include <ast.hh>
#include <lang_info.hh>

#include "config.h"

void CModuleSourceGenerator::register_builtin_type_infos()
{
    type_value_infos.clear();

    for (const auto &[name, info] : g_current_lang_info->type_infos) {
        TypeValueInfo value_info;

        value_info.c_type = info.lang_name;
        value_info.type_size = info.size;

        if (name == "handle") {
            value_info.is_pointer_like = true;
        } else if (name == "status") {
            value_info.is_integer = true;
        } else if (name.size() >= 2 && name[0] == 'u' && std::isdigit(name[1])) {
            value_info.is_integer = true;
            value_info.is_unsigned = true;
        } else if (name.size() >= 2 && name[0] == 's' && std::isdigit(name[1])) {
            value_info.is_integer = true;
        }

        type_value_infos[name] = value_info;
    }
}

CModuleSourceGenerator::TypeValueInfo CModuleSourceGenerator::get_type_value_info(TypeNode &node)
{
    if (node.inner_type && node.is_ptr) {
        TypeValueInfo info;

        info.c_type = to_c_type(prefix, node);
        info.type_size = sizeof(void *);
        info.is_pointer_like = true;
        return info;
    }

    auto builtin_it = type_value_infos.find(std::string(node.name));
    if (builtin_it != type_value_infos.end()) {
        TypeValueInfo info = builtin_it->second;
        info.c_type = to_c_type(prefix, node);
        return info;
    }

    TypeValueInfo info;

    info.c_type = to_c_type(prefix, node);
    info.type_size = node.type_size;
    return info;
}

std::string CModuleSourceGenerator::get_parameter_c_type(const ParameterNode &node)
{
    bool add_pointer = node.direction != ParameterNode::Direction::IN;

    if (node.type->is_ptr) {
        return to_c_type(prefix, *node.type) + (add_pointer ? "*" : "");
    }

    return to_c_type(prefix, *node.type) + (add_pointer ? " *" : "");
}

bool CModuleSourceGenerator::parameter_uses_pointer_argument(const ParameterNode &node)
{
    return node.direction != ParameterNode::Direction::IN || node.type->is_ptr ||
        node.type->is_array;
}

void CModuleSourceGenerator::write_dispatch_case(FunctionNode &node)
{
    out << "    case " << node.id << ": {\n";
    if (node.parameters.empty()) {
        out << "        (void)args;\n";
    } else {
        out << "\n";
    }

    for (size_t i = 0; i < node.parameters.size(); ++i) {
        const auto &param = node.parameters[i];
        std::string exact_type = get_parameter_c_type(*param);
        std::string arg_expr =
            parameter_uses_pointer_argument(*param) ? "(uintptr_t)args[" : "args[";

        out << "        " << exact_type << " " << param->name << " = (" << exact_type << ")"
            << arg_expr << i << "];\n";
    }

    out << "\n        return typed_vtable->" << node.name << "(context, handle";
    for (const auto &param : node.parameters) {
        out << ", " << param->name;
    }
    out << ");\n";
    out << "    }\n";
}

void CModuleSourceGenerator::visit(InterfaceNode &node)
{
    prefix.clear();
    macro_interface_name.clear();
    total_funcid_span = 0;
    abi_spans.clear();
    functions_by_id.clear();
    register_builtin_type_infos();

    macro_interface_name = node.name;
    std::transform(
        macro_interface_name.begin(),
        macro_interface_name.end(),
        macro_interface_name.begin(),
        [](unsigned char ch) {
            return static_cast<char>(std::toupper(ch));
        }
    );

    for (const auto &anno : node.annotations) {
        if (anno->name == "prefix") {
            if (anno->args.size() != 1) {
                throw std::runtime_error("Invalid argument size");
            }

            auto prefix_param = dynamic_cast<StringLiteralExpressionNode *>(anno->args[0].get());
            if (!prefix_param) {
                throw std::runtime_error("Invalid argument type");
            }

            prefix = prefix_param->value.substr(1, prefix_param->value.size() - 2);
        }
    }

    for (const auto &abi : node.abiversions) {
        abi->accept(*this);
    }

    out << "/* =====================================================================\n";
    out << " * Auto-generated by sidlc v" << SIDLC_VERSION << " (" << SIDLC_GIT_HASH << ")\n";
    out << " * Target Interface: " << node.name << "\n";
    out << " * DO NOT EDIT THIS FILE MANUALLY!\n";
    out << " * ===================================================================== */\n\n";

    out << "#include \"" << header_name << "\"\n\n";

    out << "StStatus " << prefix << "ModuleDispatchArgs(\n";
    out << "    const void *vtable __in,\n";
    out << "    void *context __inout,\n";
    out << "    StHandle handle __in,\n";
    out << "    uint32_t funcid __in,\n";
    out << "    const long args[6]\n";
    out << ")\n";
    out << "{\n";
    out << "    const " << prefix << "ModuleVTable *typed_vtable;\n";
    out << "    const uintptr_t *vtable_slots;\n";
    out << "\n";
    out << "    if (vtable == NULL || args == NULL) {\n";
    out << "        return STATUS_INVALID_VALUE;\n";
    out << "    }\n";
    out << "    if (funcid >= " << total_funcid_span << ") {\n";
    out << "        return STATUS_NOT_IMPLEMENTED;\n";
    out << "    }\n";
    out << "    vtable_slots = (const uintptr_t *)vtable;\n";
    out << "    if (vtable_slots[funcid] == 0) {\n";
    out << "        return STATUS_NOT_IMPLEMENTED;\n";
    out << "    }\n";
    out << "    typed_vtable = (const " << prefix << "ModuleVTable *)vtable;\n\n";
    out << "    switch (funcid) {\n";
    for (FunctionNode *function : functions_by_id) {
        if (!function) {
            continue;
        }

        write_dispatch_case(*function);
    }
    out << "    default:\n";
    out << "        return STATUS_NOT_IMPLEMENTED;\n";
    out << "    }\n";
    out << "}\n\n";
}

void CModuleSourceGenerator::visit(AbiversionNode &node)
{
    for (const auto &e : node.enums) {
        e->accept(*this);
    }

    for (const auto &b : node.bitfields) {
        b->accept(*this);
    }

    for (const auto &s : node.structs) {
        s->accept(*this);
    }

    for (const auto &f : node.functions) {
        f->accept(*this);
    }

    if (abi_spans.size() <= node.version) {
        abi_spans.resize(node.version + 1, total_funcid_span);
    }

    if (!node.functions.empty()) {
        total_funcid_span = node.functions.back()->id + 1;
    }

    abi_spans[node.version] = total_funcid_span;
}

void CModuleSourceGenerator::visit(StructNode &node)
{
    TypeValueInfo info;

    info.c_type = prefix + std::string(node.name);
    type_value_infos[std::string(node.name)] = info;
}

void CModuleSourceGenerator::visit(BitfieldNode &node)
{
    TypeValueInfo info = get_type_value_info(*node.base_type);

    info.c_type = prefix + std::string(node.name);
    info.is_pointer_like = false;
    type_value_infos[std::string(node.name)] = info;
}

void CModuleSourceGenerator::visit(EnumNode &node)
{
    TypeValueInfo info = get_type_value_info(*node.base_type);

    info.c_type = prefix + std::string(node.name);
    info.is_pointer_like = false;
    type_value_infos[std::string(node.name)] = info;
}

void CModuleSourceGenerator::visit(FunctionNode &node)
{
    if (functions_by_id.size() <= node.id) {
        functions_by_id.resize(node.id + 1, nullptr);
    }

    functions_by_id[node.id] = &node;
}
