#include <c_module_source_generator.hh>

#include <algorithm>
#include <cctype>
#include <stdexcept>

#include <uuid.h>

#include <ast.hh>

#include "config.h"

void CModuleSourceGenerator::visit(InterfaceNode &node)
{
    prefix.clear();
    macro_interface_name.clear();
    total_funcid_span = 0;
    abi_spans.clear();

    buf_macros.str("");
    buf_macros.clear();
    buf_function_decls.str("");
    buf_function_decls.clear();
    buf_function_defs.str("");
    buf_function_defs.clear();
    buf_function_table.str("");
    buf_function_table.clear();

    macro_interface_name = node.name;
    std::transform(
        macro_interface_name.begin(),
        macro_interface_name.end(),
        macro_interface_name.begin(),
        [](unsigned char ch) {
            return static_cast<char>(std::toupper(ch));
        }
    );

    for (const auto &anno : node.annotations) {
        if (anno->name == "prefix") {
            if (anno->args.size() != 1) {
                throw std::runtime_error("Invalid argument size");
            }

            auto prefix_param = dynamic_cast<StringLiteralExpressionNode *>(anno->args[0].get());
            if (!prefix_param) {
                throw std::runtime_error("Invalid argument type");
            }

            prefix = prefix_param->value.substr(1, prefix_param->value.size() - 2);
        }
    }

    buf_function_table << "static const void *const functions[] = {\n";

    for (const auto &abi : node.abiversions) {
        abi->accept(*this);
    }

    buf_function_table << "};\n\n";

    out << "/* =====================================================================\n";
    out << " * Auto-generated by sidlc v" << SIDLC_VERSION << " (" << SIDLC_GIT_HASH << ")\n";
    out << " * Target Interface: " << node.name << "\n";
    out << " * DO NOT EDIT THIS FILE MANUALLY!\n";
    out << " * ===================================================================== */\n\n";

    out << "#include \"" << header_name << "\"\n\n";
    out << "#include <stddef.h>\n";
    out << "#include <stdint.h>\n\n";
    out << "#include <strata/status.h>\n";
    out << "#include <strata/macros.h>\n";
    out << "#include <strata/uuid.h>\n\n";

    if (buf_macros.tellp() > 0) {
        out << "/* Constants & Bitmasks */\n";
        out << buf_macros.str() << "\n";
    }

    out << "static const struct StUuid interface_uuid = "
        << "UUID_" << macro_interface_name << "_INTERFACE_INIT;\n\n";

    if (buf_function_decls.tellp() > 0) {
        out << "/* Functions & Views */\n";
        out << buf_function_decls.str() << "\n";
    }

    out << "/* Module Interface Metadata */\n";
    out << "struct StSidl_ModuleInterface {\n";
    out << "    struct StUuid uuid;\n";
    out << "    uint32_t funcid_span;\n";
    out << "    const uint32_t *abi_funcid_spans;\n";
    out << "    size_t abi_revision_count;\n";
    out << "    const void *const *functions;\n";
    out << "};\n\n";

    out << buf_function_table.str();

    out << "static const uint32_t abi_funcid_spans[] = {\n";
    for (size_t i = 0; i < abi_spans.size(); ++i) {
        out << "    [" << i << "] = " << abi_spans[i] << ",\n";
    }
    out << "};\n\n";

    out << "const struct StSidl_ModuleInterface " << prefix << "ModuleInterface = {\n";
    out << "    .uuid = interface_uuid,\n";
    out << "    .funcid_span = " << total_funcid_span << ",\n";
    out << "    .abi_funcid_spans = abi_funcid_spans,\n";
    out << "    .abi_revision_count = ARRAY_SIZE(abi_funcid_spans),\n";
    out << "    .functions = functions,\n";
    out << "};\n";
}

void CModuleSourceGenerator::visit(AbiversionNode &node)
{
    if (!node.functions.empty()) {
        buf_macros << "\n/* ABI Version " << node.version << " */\n";
        buf_function_decls << "\n/* ABI Version " << node.version << " */\n";
    }

    for (const auto &f : node.functions) {
        f->accept(*this);
    }

    if (abi_spans.size() <= node.version) {
        abi_spans.resize(node.version + 1, total_funcid_span);
    }

    if (!node.functions.empty()) {
        total_funcid_span = node.functions.back()->id + 1;
    }

    abi_spans[node.version] = total_funcid_span;
}

void CModuleSourceGenerator::visit(FunctionNode &node)
{
    buf_macros << "#define FUNCID_" << node.name << " " << node.id << "\n";

    if (node.parameters.empty()) {
        buf_function_decls << "extern StStatus " << prefix << node.name << "(StHandle handle __in";
    } else {
        buf_function_decls << "extern StStatus " << prefix << node.name << "(StHandle handle __in, ";
    }

    for (const auto &param : node.parameters) {
        bool add_pointer = param->direction != ParameterNode::Direction::IN;

        if (param->type->is_ptr) {
            buf_function_decls << to_c_type(prefix, *param->type) << (add_pointer ? "*" : "")
                               << param->name;
        } else {
            buf_function_decls << to_c_type(prefix, *param->type) << (add_pointer ? " *" : " ")
                               << param->name;
        }

        switch (param->direction) {
        case ParameterNode::Direction::IN:
            buf_function_decls << " __in";
            break;
        case ParameterNode::Direction::OUT:
            buf_function_decls << " __out";
            break;
        case ParameterNode::Direction::INOUT:
            buf_function_decls << " __inout";
            break;
        }

        if (&param != &node.parameters.back()) {
            buf_function_decls << ", ";
        }
    }

    buf_function_decls << ");\n";

    buf_function_table << "    [FUNCID_" << node.name << "] = (const void *)(uintptr_t)" << prefix
                       << node.name << ",\n";
}
