#include <c_user_source_generator.hh>

#include <algorithm>
#include <cctype>
#include <stdexcept>

#include <uuid.h>

#include <arch_abi.hh>
#include <ast.hh>

#include "config.h"

void CUserSourceGenerator::visit(InterfaceNode &node)
{
    macro_interface_name = node.name;
    std::transform(
        macro_interface_name.begin(),
        macro_interface_name.end(),
        macro_interface_name.begin(),
        ::toupper
    );

    if (!node.has_prefix) {
        throw std::runtime_error("Interface prefix is required");
    }
    prefix = node.prefix;

    for (const auto &anno : node.annotations) {
        if (anno->name == "prefix") {
            throw std::runtime_error("Prefix must be stored as interface metadata, not annotation");
        }
    }

    for (const auto &abi : node.abiversions) {
        abi->accept(*this);
    }

    out << "/* =====================================================================\n";
    out << " * Auto-generated by sidlc v" << SIDLC_VERSION << " (" << SIDLC_GIT_HASH << ")\n";
    out << " * Target Interface: " << node.name << "\n";
    out << " * DO NOT EDIT THIS FILE MANUALLY!\n";
    out << " * ===================================================================== */\n\n";

    out << "#include \"" << header_name << "\"\n\n";
    out << "#include <stdint.h>\n\n";
    out << "#include <strata/status.h>\n";
    out << "#include <strata/macros.h>\n";
    out << "#include <strata/uuid.h>\n";
    out << "\n";

    if (buf_macros.tellp() > 0) {
        out << "/* Constants & Bitmasks */\n";
        out << buf_macros.str() << "\n";
    }

    out << "static const struct StUuid interface_uuid = "
        << "UUID_" << macro_interface_name << "_INTERFACE_INIT;\n\n";

    if (emit_handle_binding) {
        out << "StStatus " << prefix
            << "Open(const uint8_t *path __in, uint32_t flags __in, StHandle *handle __out)\n";
        out << "{\n";
        out << "    return StHandle_Open(path, flags, handle);\n";
        out << "}\n\n";
        out << "StStatus " << prefix
            << "Query(StHandle handle __in, uint32_t request_abiver __in, "
               "uint32_t *funcid_base __out, uint32_t *result_abiver __out)\n";
        out << "{\n";
        out << "    return StHandle_Query(handle, &interface_uuid, request_abiver, funcid_base, "
               "result_abiver);\n";
        out << "}\n\n";
    }

    if (buf_functions.tellp() > 0) {
        out << "/* Functions & Views */\n";
        out << buf_functions.str() << "\n";
    }
}

void CUserSourceGenerator::visit(AbiversionNode &node)
{
    if (!node.functions.empty()) {
        buf_macros << "\n/* ABI Version " << node.version << " */\n";
        buf_functions << "\n/* ABI Version " << node.version << " */\n";
    }

    for (const auto &f : node.functions) {
        f->accept(*this);
    }
}

void CUserSourceGenerator::visit(FunctionNode &node)
{
    buf_macros << "#define FUNCID_" << node.name << " " << node.id << "\n";

    if (make_weak_symbols) {
        buf_functions << "__attribute__((weak))\n";
    }
    if (node.parameters.empty()) {
        buf_functions << "StStatus " << prefix << node.name << "(StHandle handle __in";
    } else {
        buf_functions << "StStatus " << prefix << node.name << "(StHandle handle __in, ";
    }

    for (const auto &param : node.parameters) {
        bool add_pointer = param->direction != ParameterNode::Direction::IN;

        if (param->type->is_ptr) {
            buf_functions << to_c_type(prefix, *param->type) << (add_pointer ? "*_" : "_")
                          << param->name;
        } else {
            buf_functions << to_c_type(prefix, *param->type) << (add_pointer ? " *_" : " _")
                          << param->name;
        }

        switch (param->direction) {
        case ParameterNode::Direction::IN:
            buf_functions << " __in";
            break;
        case ParameterNode::Direction::OUT:
            buf_functions << " __out";
            break;
        case ParameterNode::Direction::INOUT:
            buf_functions << " __inout";
            break;
        }

        if (&param != &node.parameters.back()) {
            buf_functions << ", ";
        }
    }

    buf_functions << ")\n";

    bool can_use_call_reg = true;
    size_t k_base = 2;
    size_t n_avail = g_current_arch_abi->max_reg_args - k_base;
    size_t k_peel = n_avail > 2 ? n_avail - 2 : 0;

    if (node.parameters.size() > n_avail) {
        can_use_call_reg = false;
    }

    std::vector<ParameterNode *> peeled_params;
    std::vector<ParameterNode *> in_params;
    std::vector<ParameterNode *> out_params;

    for (const auto &param : node.parameters) {
        bool is_scalar = param->direction == ParameterNode::Direction::IN && !param->type->is_ptr &&
            !param->type->is_array && param->type->type_size <= g_current_arch_abi->pointer_size;

        if (!is_scalar) {
            can_use_call_reg = false;
        }

        if (param->direction == ParameterNode::Direction::OUT) {
            out_params.push_back(param.get());
        } else {
            if (is_scalar && peeled_params.size() < k_peel) {
                peeled_params.push_back(param.get());
            } else {
                in_params.push_back(param.get());
            }
        }
    }

    buf_functions << "{\n";
    buf_functions << "    StStatus status;\n";
    buf_functions << "    uint32_t funcid_base;\n";

    if (!can_use_call_reg && !in_params.empty()) {
        if (in_params.size() > 1) {
            buf_functions << "    struct {\n";
            for (const auto &param : in_params) {
                switch (param->direction) {
                case ParameterNode::Direction::IN:
                    if (param->type->is_ptr) {
                        buf_functions << "        " << to_c_type(prefix, *param->type)
                                      << param->name << ";\n";
                    } else {
                        buf_functions << "        " << to_c_type(prefix, *param->type) << " "
                                      << param->name << ";\n";
                    }
                    break;
                case ParameterNode::Direction::INOUT:
                    if (param->type->is_ptr) {
                        buf_functions << "        " << to_c_type(prefix, *param->type) << "*"
                                      << param->name << ";\n";
                    } else {
                        buf_functions << "        " << to_c_type(prefix, *param->type) << " *"
                                      << param->name << ";\n";
                    }
                    break;
                case ParameterNode::Direction::OUT:
                    break;
                }
            }
            buf_functions << "    } in = {\n";
            for (const auto &param : in_params) {
                if (param->type->is_ptr) {
                    buf_functions << "        ." << param->name << " = _" << param->name << ",\n";
                } else {
                    buf_functions << "        ." << param->name << " = _" << param->name << ",\n";
                }
            }
            buf_functions << "    };\n";
        }
    }
    if (!can_use_call_reg && !out_params.empty()) {
        if (out_params.size() > 1) {
            buf_functions << "    struct {\n";
            for (const auto &param : out_params) {
                if (param->type->is_ptr) {
                    buf_functions << "        " << to_c_type(prefix, *param->type) << param->name
                                  << ";\n";
                } else {
                    buf_functions << "        " << to_c_type(prefix, *param->type) << " "
                                  << param->name << ";\n";
                }
            }
            buf_functions << "    } out;\n";
        } else if (!out_params.front()->type->is_ptr) {
            buf_functions << "    " << to_c_type(prefix, *out_params.front()->type)
                          << " out;\n";
        }
    }
    buf_functions << "    status = StHandle_Query(handle, &interface_uuid, 0, &funcid_base, NULL);\n";
    buf_functions << "    if (!CHECK_SUCCESS(status)) { return status; }\n";

    if (can_use_call_reg) {
        buf_functions << "    status = StHandle_Call" << node.parameters.size()
                      << "(handle, funcid_base + FUNCID_" << node.name;
        for (size_t i = 0; i < node.parameters.size(); ++i) {
            buf_functions << ", (unsigned long)_" << node.parameters[i]->name;
        }
        buf_functions << ");\n";
    } else {
        buf_functions << "    status = StHandle_CallN(handle, funcid_base + FUNCID_" << node.name
                      << ", ";
        if (!in_params.empty()) {
            if (in_params.size() == 1) {
                if (in_params.front()->type->is_ptr) {
                    buf_functions << "(const void *)_" << in_params.front()->name << ", ";
                } else {
                    buf_functions << "(const void *)&_" << in_params.front()->name << ", ";
                }
            } else {
                buf_functions << "(const void *)&in, ";
            }
        } else {
            buf_functions << "NULL, ";
        }
        if (!out_params.empty()) {
            if (out_params.size() == 1) {
                if (out_params.front()->type->is_ptr) {
                    buf_functions << "(void *)_" << out_params.front()->name << ", ";
                } else {
                    buf_functions << "(void *)&out, ";
                }
            } else {
                buf_functions << "(void *)&out, ";
            }
        } else {
            buf_functions << "NULL, ";
        }
        for (size_t i = 0; i < k_peel; ++i) {
            if (i < peeled_params.size()) {
                buf_functions << "(unsigned long)_" << peeled_params[i]->name;
            } else {
                buf_functions << "0";
            }
            if (i < k_peel - 1) {
                buf_functions << ", ";
            }
        }
        buf_functions << ");\n";
    }
    buf_functions << "    if (!CHECK_SUCCESS(status)) { return status; }\n";

    if (!can_use_call_reg && !out_params.empty()) {
        if (out_params.size() == 1) {
            auto param = out_params.front();
            if (!param->type->is_ptr) {
                buf_functions << "    if (_" << param->name << " != NULL) "
                              << "{ *_" << param->name << " = out; }\n";
            }
        } else {
            for (const auto &param : out_params) {
                buf_functions << "    if (_" << param->name << " != NULL) "
                              << "{ *_" << param->name << " = out." << param->name << "; }\n";
            }
        }
    }

    buf_functions << "    return STATUS_SUCCESS;\n";
    buf_functions << "}\n\n";
}
